Import('env','libs')

files=Glob('*.cc',strings=True)
tnames=['gnksa-test','message-check-test','numbers-test','scorefile-test'
        ,'text-massager-test','url-find-test']
tfiles=[x+'.cc' for x in tnames]
for x in tfiles:
    files.remove(x)

l=env.StaticLibrary('usenet_utils',files)
libs.insert(0,l)

t=[]
for x in range(0,len(tnames)) :
    t.append(env.Program(tnames[x],tfiles[x],LIBS=libs))

env.Alias('tests',t)


