Import('env','libs')

files=Glob('*.cc',strings=True)
files.remove('progress-test.cc')
files.remove('quark-test.cc')
files.remove('string-view-test.cc')
files.remove('text-match-test.cc')

l=env.StaticLibrary('general',files)
libs.append(l)

t=[]
t.append(env.Program('progress-test','progress-test.cc',LIBS=l))
t.append(env.Program('quark-test','quark-test.cc',LIBS=l))
t.append(env.Program('string-view-test','string-view-test.cc',LIBS=l))
t.append(env.Program('text-match-test','text-match-test.cc',LIBS=l))

env.Alias('tests',t)


