Import('env','libs')

libs2=libs
libs=[]
SConscript('icons/SConscript',exports=['env'])
SConscript('general/SConscript',exports=['env','libs'])
SConscript('usenet-utils/SConscript',exports=['env','libs'])
SConscript('data/SConscript',exports=['env','libs'])
SConscript('data-impl/SConscript',exports=['env','libs'])
SConscript('tasks/SConscript',exports=['env','libs'])
libs=libs+libs2
SConscript('gui/SConscript',exports=['env','libs'])

#env.Install('pan.cfg','pan.cfg')
