Import('env','libs')

files=Glob('*.cc',strings=True)
files.remove('pan.cc')

l=env.StaticLibrary('pangui',files)
libs.insert(0,l)

if Platform().name=='win32':
    rc=env.RES('panrc','panrc.rc')
    files.append(rc)
    
pan=env.Program('pan','pan.cc',LIBS=libs)

env.Alias('pan',pan)
env.Default(pan)


